ALTER TABLE otp_codes ADD COLUMN attempts INT NOT NULL DEFAULT 0;

CREATE TABLE revoked_tokens (
    token_id VARCHAR(255) PRIMARY KEY,
    revoked_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
