spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/obs}
spring.datasource.username=${DB_USERNAME:obs}
spring.datasource.password=${DB_PASSWORD:obs}

spring.flyway.locations=classpath:db/migration

